version: 0.1.{build}
image: Visual Studio 2017
configuration: Release

environment:
   packageVersion: 0.1.0

init:
- ps: $env:buildVersion = "$env:packageVersion.$env:APPVEYOR_BUILD_NUMBER"
- ps: $env:nugetVersionSuffix = @{ $false = "beta-{0:00000}" -f [convert]::ToInt32("0" + $env:APPVEYOR_BUILD_NUMBER, 10); $true = "" }[ $env:APPVEYOR_REPO_BRANCH -eq "master" ]
- ps: 'Write-Host "buildVersion: $($env:buildVersion)"'
- ps: 'Write-Host "nugetVersionSuffix: $($env:nugetVersionSuffix)"'
- ps: Update-AppveyorBuild -Version $env:buildVersion

#assembly_info:
#  patch: true
#  file: '**\AssemblyInfo.*'
#  assembly_version: '{version}'
#  assembly_file_version: '{version}'
#  assembly_informational_version: '{version}'

dotnet_csproj:
   patch: true
   file: '**\*.csproj'
   version: '{packageVersion}'
   assembly_version: '{version}'
   file_version: '{version}'
   informational_version: '{version}'

nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true

install:
- cmd: dotnet restore

#before_build:
#- cmd: nuget restore

build:
  publish_nuget: false
  verbosity: minimal

after_build:
- ps: 'dotnet pack src\Alphaleonis.Reflection -o .\artifacts --version-suffix "alpha" --no-restore --no-build'

artifacts:
- path: '**\*.nupkg'
  name: nuget-package

deploy:
   provider: NuGet
   server: https://ci.appveyor.com/nuget/alphaleonis-rsgpyjhi2c6t/api/v2/package
   api_key:
      secure: PnuQGphn/9gGaVZRnUejvcijO8H5cJyoYPAekBvC4n8=
   skip_symbols: true
   artifact: /.*\.nupkg/

#deploy:
#- provider: NuGet
#  api_key:
#    secure: kKYxxjMz8YoTTjZ6ccVtkPXhadPrXgW2SWYxwcDlFDx75i+xVm4veu4p1QJQBSOF
#  skip_symbols: true
#  on:
#    branch: master