version: 0.1.{build}
image: Visual Studio 2017
configuration: Release

environment:
   packageVersion: 0.1.0

init:
- ps: $env:buildVersion = "$env:packageVersion.$env:appveyor_build_number"
- ps: $env:nugetVersion = "$env:packageVersion-beta-$env:appveyor_build_number"
- ps: Update-AppveyorBuild -Version $env:buildVersion

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true

before_build:
- cmd: nuget restore

build:
  publish_nuget: false
  verbosity: minimal

after_build:
- ps: nuget pack src\Alphaleonis.Reflection\Alphaleonis.Reflection.nuspec -OutputDirectory .\artifacts -version "$env:nugetVersion"

#deploy:
#- provider: NuGet
#  api_key:
#    secure: kKYxxjMz8YoTTjZ6ccVtkPXhadPrXgW2SWYxwcDlFDx75i+xVm4veu4p1QJQBSOF
#  skip_symbols: true
#  on:
#    branch: master